// Xbox 360 games that are backward-compatible on Xbox One & Series X|S.
// Source: Microsoft / Wikipedia backward-compatibility list (program closed 2021).
// Keys are normalized titles (see lib/match.ts normalize()). 615 titles.
export const XBOX360_BC = new Set<string>([
  "0 day attack on earth",
  "3d ultra minigolf adventures",
  "50 cent blood on the sand",
  "a kingdom for keflings",
  "a world of keflings",
  "ace combat 6 fires of liberation",
  "aces of the galaxy",
  "adventure time the secret of the nameless kingdom",
  "aegis wing",
  "age of booty",
  "airmech arena",
  "alan wake",
  "alan wake s american nightmare",
  "alex kidd in miracle world",
  "alice madness returns",
  "alien hominid hd",
  "aliens vs predator",
  "altered beast",
  "anomaly warzone earth",
  "aqua",
  "are you smarter than a 5th grader",
  "arkanoid live",
  "army of two",
  "assassin s creed",
  "assassin s creed brotherhood",
  "assassin s creed ii",
  "assassin s creed iii",
  "assassin s creed iv black flag",
  "assassin s creed liberation hd",
  "assassin s creed revelations",
  "assassin s creed rogue",
  "assault heroes 2",
  "asteroids deluxe",
  "astropop",
  "asura s wrath",
  "avatar the last airbender the burning earth",
  "axel pixel",
  "babel rising",
  "band of bugs",
  "banjo kazooie",
  "banjo kazooie nuts bolts",
  "banjo tooie",
  "bankshot billiards 2",
  "batman arkham origins",
  "battleblock theater",
  "battlefield 1943",
  "battlefield 2 modern combat",
  "battlefield 3",
  "battlefield bad company",
  "battlefield bad company 2",
  "battlestations midway",
  "battlestations pacific",
  "bayonetta",
  "beat n groovy",
  "beautiful katamari",
  "bejeweled 2",
  "bejeweled 3",
  "bellator mma onslaught",
  "beyond good evil hd",
  "binary domain",
  "bionic commando rearmed 2",
  "bioshock",
  "bioshock 2",
  "bioshock infinite",
  "black college football bcfx the xperience",
  "blazing angels squadrons of wwii",
  "blood knights",
  "blood of the werewolf",
  "bloodforge",
  "bloodrayne betrayal",
  "blue dragon",
  "bolt",
  "bomberman live battlefest",
  "boom boom rocket",
  "borderlands",
  "borderlands 2",
  "bound by flame",
  "braid",
  "brain challenge",
  "brave the video game",
  "brothers in arms hell s highway",
  "brutal legend",
  "bully scholarship edition",
  "burnout paradise",
  "burnout revenge",
  "cabela s alaskan adventures",
  "cabela s dangerous hunts 2013",
  "cabela s hunting expeditions",
  "cabela s survival shadows of katmai",
  "call of duty 2",
  "call of duty 3",
  "call of duty 4 modern warfare",
  "call of duty advanced warfare",
  "call of duty black ops",
  "call of duty black ops ii",
  "call of duty ghosts",
  "call of duty modern warfare 2",
  "call of duty modern warfare 3",
  "call of duty world at war",
  "call of juarez bound in blood",
  "call of juarez gunslinger",
  "call of juarez the cartel",
  "capcom arcade cabinet",
  "carcassonne",
  "cars 2 the video game",
  "cars mater national championship",
  "castle crashers",
  "castle of illusion starring mickey mouse",
  "castlestorm",
  "castlevania harmony of despair",
  "castlevania lords of shadow",
  "castlevania lords of shadow 2",
  "castlevania lords of shadow mirror of fate hd",
  "castlevania symphony of the night",
  "catherine",
  "centipede millipede",
  "child of eden",
  "clannad",
  "cloning clyde",
  "comic jumper the adventures of captain smiley",
  "comix zone",
  "command conquer 3 kane s wrath",
  "command conquer 3 tiberium wars",
  "command conquer red alert 3",
  "command conquer red alert 3 commander s challenge",
  "commanders attack of the genos",
  "conan",
  "condemned criminal origins",
  "contra",
  "costume quest",
  "costume quest 2",
  "counter strike global offensive",
  "crackdown",
  "crackdown 2",
  "crazy taxi",
  "crysis",
  "crysis 2",
  "crysis 3",
  "crystal defenders",
  "crystal quest",
  "cyber troopers virtual on",
  "cyber troopers virtual on oratorio tangram",
  "dante s inferno",
  "dark souls",
  "dark void",
  "darksiders",
  "darksiders ii",
  "darwinia",
  "daytona usa",
  "de blob 2",
  "dead or alive 4",
  "dead rising 2 case west",
  "dead rising 2 case zero",
  "dead space",
  "dead space 2",
  "dead space 3",
  "dead space ignition",
  "deadfall adventures",
  "deadliest warrior legends",
  "deadliest warrior the game",
  "deadly premonition",
  "death by cube",
  "deathspank thongs of virtue",
  "defense grid the awakening",
  "deus ex human revolution",
  "deus ex human revolution director s cut",
  "dig dug",
  "dirt 3",
  "dirt showdown",
  "discs of tron",
  "disney universe",
  "divinity ii",
  "domino master",
  "doom",
  "doom 3 bfg edition",
  "doom ii hell on earth",
  "doritos crash course",
  "double dragon neon",
  "dragon age ii",
  "dragon age origins",
  "dragon s lair",
  "driver san francisco",
  "ducktales remastered",
  "duke nukem forever",
  "duke nukem manhattan project",
  "dungeon siege iii",
  "dungeons dragons chronicles of mystara",
  "earth defense force 2017",
  "earth defense force 2025",
  "earth defense force insect armageddon",
  "earthworm jim hd",
  "eat lead the return of matt hazard",
  "elements of destruction",
  "enchanted arms",
  "enslaved odyssey to the west",
  "epic mickey 2 the power of two",
  "escape dead island",
  "every extend extra extreme",
  "f e a r",
  "f e a r 2 project origin",
  "f e a r 3",
  "f e a r files",
  "f1 2014",
  "fable anniversary",
  "fable heroes",
  "fable ii",
  "fable ii pub games",
  "fable iii",
  "faery legends of avalon",
  "fallout 3",
  "fallout new vegas",
  "far cry 2",
  "far cry 3",
  "far cry 3 blood dragon",
  "far cry classic",
  "far cry instincts predator",
  "feeding frenzy",
  "feeding frenzy 2 shipwreck showdown",
  "fight night champion",
  "fighting vipers",
  "final fantasy xiii",
  "final fantasy xiii 2",
  "final fight double impact",
  "flashback",
  "flock",
  "forza horizon",
  "foul play",
  "fret nice",
  "frogger",
  "frogger 2",
  "from dust",
  "frontlines fuel of war",
  "fuel",
  "funtown mahjong",
  "galaga",
  "galaga legions",
  "galaga legions dx",
  "garou mark of the wolves",
  "gatling gears",
  "gears of war",
  "gears of war 2",
  "gears of war 3",
  "gears of war judgment",
  "geometry wars 3 dimensions",
  "geometry wars retro evolved",
  "geometry wars retro evolved 2",
  "ghostbusters sanctum of slime",
  "ghostbusters the video game",
  "gin rummy",
  "girl fight",
  "go go break steady",
  "goat simulator",
  "golden axe",
  "golf tee it up",
  "grand theft auto iv",
  "grand theft auto san andreas",
  "grid 2",
  "grid autosport",
  "gripshift",
  "guardian heroes",
  "gunstar heroes",
  "guwange",
  "gyromancer",
  "gyruss",
  "half minute hero super mega neo climax",
  "halo 3",
  "halo 3 odst campaign edition",
  "halo 4",
  "halo combat evolved anniversary",
  "halo reach",
  "halo spartan assault",
  "halo wars",
  "hard corps uprising",
  "harms way",
  "haunted house",
  "heavy weapon",
  "hexic 2",
  "hexic hd",
  "hitman absolution",
  "hitman blood money",
  "hydro thunder hurricane",
  "hydrophobia",
  "i am alive",
  "ikaruga",
  "ilomilo",
  "infinite undiscovery",
  "injustice gods among us",
  "insanely twisted shadow planet",
  "interpol the trail of dr chaos",
  "iron brigade",
  "islands of wakfu",
  "jet set radio hd",
  "jetpac refuelled",
  "jewel quest",
  "joe danger 2 the movie",
  "joe danger special edition",
  "joust",
  "joy ride turbo",
  "juju",
  "jurassic park the game",
  "just cause",
  "just cause 2",
  "kameo",
  "kane lynch 2 dog days",
  "killer is dead",
  "king of fighters sky stage",
  "kingdoms of amalur reckoning",
  "lara croft and the guardian of light",
  "lazy raiders",
  "left 4 dead",
  "left 4 dead 2",
  "lego batman 2 dc super heroes",
  "lego batman the videogame",
  "lego indiana jones 2 the adventure continues",
  "lego indiana jones the original adventures",
  "lego pirates of the caribbean the video game",
  "lego star wars ii the original trilogy",
  "lego star wars iii the clone wars",
  "lego star wars the complete saga",
  "lego the lord of the rings",
  "lightning returns final fantasy xiii",
  "limbo",
  "lode runner",
  "lost odyssey",
  "lost planet 2",
  "lost planet 3",
  "lost planet colonies",
  "lost planet extreme condition",
  "lumines live",
  "luxor 2",
  "mad tracks",
  "madballs in babo invasion",
  "mafia ii",
  "magic the gathering duels of the planeswalkers",
  "magic the gathering duels of the planeswalkers 2012",
  "magic the gathering duels of the planeswalkers 2013",
  "magic the gathering duels of the planeswalkers 2014",
  "marathon 2 durandal",
  "marlow briggs and the mask of death",
  "mars war logs",
  "mass effect",
  "mass effect 2",
  "mass effect 3",
  "matt hazard blood bath and beyond",
  "max payne 3",
  "medal of honor airborne",
  "meet the robinsons",
  "mega man 10",
  "mega man 9",
  "metal gear rising revengeance",
  "metal gear solid hd collection",
  "metal gear solid peace walker hd edition",
  "metal slug 3",
  "metal slug xx",
  "midnight club los angeles",
  "midway arcade origins",
  "might magic clash of heroes",
  "military madness nectaris",
  "mini ninjas",
  "mirror s edge",
  "missile command",
  "monaco what s yours is mine",
  "monday night combat",
  "monkey island 2 special edition lechuck s revenge",
  "monopoly deal",
  "monopoly plus",
  "moon diver",
  "mortal kombat",
  "mortal kombat vs dc universe",
  "motocross madness",
  "mr driller online",
  "ms pac man",
  "ms splosion man",
  "mutant storm empire",
  "mutant storm reloaded",
  "mx vs atv alive",
  "mx vs atv reflex",
  "mx vs atv untamed",
  "n",
  "nba jam on fire edition",
  "neogeo battle coliseum",
  "new rally x",
  "nier",
  "nights into dreams",
  "ninja gaiden 3 razor s edge",
  "ninja gaiden ii",
  "novadrome",
  "of orcs and men",
  "omega five",
  "onechanbara bikini samurai squad",
  "operation flashpoint dragon rising",
  "operation flashpoint red river",
  "orcs must die",
  "outland",
  "outpost kaloki x",
  "overlord",
  "overlord ii",
  "pac man",
  "pac man championship edition",
  "pac man championship edition dx",
  "pac man museum",
  "peggle",
  "peggle 2",
  "perfect dark",
  "perfect dark zero",
  "persona 4 arena",
  "peter jackson s king kong",
  "phantasy star ii",
  "phantom breaker battle grounds",
  "pinball fx",
  "planets under attack",
  "plants vs zombies",
  "port royale 3 pirates merchants",
  "portal 2",
  "portal still alive",
  "prince of persia",
  "prince of persia classic",
  "prince of persia the forgotten sands",
  "pure",
  "putty squad",
  "puzzle quest 2",
  "puzzle quest challenge of the warlords",
  "puzzle quest galactrix",
  "puzzlegeddon",
  "qix",
  "quake arena arcade",
  "quantum conundrum",
  "r type dimensions",
  "r u s e",
  "radiant silvergun",
  "rage",
  "raiden iv",
  "raskulls",
  "rayman 3 hd",
  "rayman legends",
  "rayman origins",
  "rayman raving rabbids",
  "red dead redemption",
  "red faction armageddon",
  "red faction battlegrounds",
  "resident evil code veronica x",
  "resident evil operation raccoon city",
  "ridge racer 6",
  "rio",
  "risen",
  "risen 2 dark waters",
  "roboblitz",
  "rock of ages",
  "rocket knight",
  "rockstar games presents table tennis",
  "rumble roses xx",
  "runner2",
  "sacred 2 fallen angel",
  "sacred 3",
  "sacred citadel",
  "saints row",
  "saints row 2",
  "saints row gat out of hell",
  "saints row iv",
  "saints row the third",
  "sam max beyond time and space",
  "sam max save the world",
  "samurai shodown ii",
  "scarygirl",
  "scramble",
  "scrap metal",
  "screamride",
  "screwjumper",
  "sega bass fishing",
  "sensible world of soccer",
  "shadow assault tenchu",
  "shadow complex",
  "shadowrun",
  "shadows of the damned",
  "shank 2",
  "shinobi",
  "shotest shogi",
  "shred nebula",
  "sid meier s civilization revolution",
  "silent hill downpour",
  "silent hill hd collection",
  "silent hill homecoming",
  "sine mora",
  "skate",
  "skate 2",
  "skate 3",
  "skullgirls encore",
  "slender the arrival",
  "small arms",
  "sniper elite v2",
  "soltrio solitaire",
  "sonic adventure",
  "sonic adventure 2",
  "sonic all stars racing transformed",
  "sonic cd",
  "sonic generations",
  "sonic knuckles",
  "sonic the fighters",
  "sonic the hedgehog",
  "sonic the hedgehog 2",
  "sonic the hedgehog 3",
  "sonic the hedgehog 4 episode i",
  "sonic the hedgehog 4 episode ii",
  "sonic unleashed",
  "soulcalibur",
  "soulcalibur ii hd online",
  "south park the stick of truth",
  "space ark",
  "space giraffe",
  "space invaders infinity gene",
  "spec ops the line",
  "spelunky",
  "split second",
  "splosion man",
  "spongebob s truth or square",
  "spongebob squarepants underpants slam",
  "ssx",
  "stacking",
  "star ocean the last hope",
  "star wars the force unleashed",
  "star wars the force unleashed ii",
  "steins gate",
  "steins gate hiyoku renri no darling",
  "steins gate senkei kosoku no phenogram",
  "street fighter iv",
  "streets of rage",
  "stuntman ignition",
  "super contra",
  "super meat boy",
  "super puzzle fighter ii turbo hd remix",
  "super street fighter iv",
  "super street fighter iv arcade edition",
  "supreme commander 2",
  "switchball",
  "syberia",
  "syndicate",
  "tales from space mutant blobs attack",
  "tecmo bowl throwback",
  "tekken 6",
  "tekken tag tournament 2",
  "texas hold em",
  "the bureau xcom declassified",
  "the cave",
  "the darkness",
  "the darkness ii",
  "the elder scrolls iv oblivion",
  "the first templar",
  "the king of fighters 2002 unlimited match",
  "the king of fighters 98 ultimate match",
  "the king of fighters xiii",
  "the maw",
  "the misadventures of p b winterbottom",
  "the orange box",
  "the outfit",
  "the secret of monkey island special edition",
  "the splatters",
  "the walking dead",
  "the walking dead michonne",
  "the walking dead season two",
  "the witcher 2 assassins of kings",
  "thrillville off the rails",
  "ticket to ride",
  "time pilot",
  "timeshift",
  "toejam earl",
  "tom clancy s endwar",
  "tom clancy s ghost recon advanced warfighter",
  "tom clancy s ghost recon advanced warfighter 2",
  "tom clancy s ghost recon future soldier",
  "tom clancy s h a w x",
  "tom clancy s rainbow six vegas",
  "tom clancy s rainbow six vegas 2",
  "tom clancy s splinter cell blacklist",
  "tom clancy s splinter cell conviction",
  "tom clancy s splinter cell double agent",
  "tomb raider anniversary",
  "tomb raider legend",
  "tomb raider underworld",
  "too human",
  "torchlight",
  "tour de france 2011",
  "toy soldiers",
  "toy soldiers cold war",
  "toy story 3",
  "toy story mania",
  "toybox turbos",
  "trials evolution",
  "trials hd",
  "triggerheart exelica",
  "trine 2",
  "tron evolution",
  "tropico 4",
  "ugly americans apocalypsegeddon",
  "ultra street fighter iv",
  "unbound saga",
  "undertow",
  "unreal tournament 3",
  "vandal hearts flames of judgment",
  "vanquish",
  "virtua fighter 2",
  "virtua fighter 5 final showdown",
  "viva pinata",
  "viva pinata party animals",
  "viva pinata trouble in paradise",
  "warlords",
  "wolf of the battlefield commando 3",
  "wolfenstein 3d",
  "wonder boy in monster land",
  "word puzzle",
  "xcom enemy unknown",
  "xcom enemy within",
  "yosumin live",
  "zone of the enders hd collection",
  "zuma",
  "zuma s revenge",
]);
